/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__transcendentals
#define __PYX_HAVE__transcendentals


#ifndef __PYX_HAVE_API__transcendentals

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(double) get_e(void);

__PYX_EXTERN_C DL_IMPORT(double) PI;

#endif /* !__PYX_HAVE_API__transcendentals */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittranscendentals(void);
#else
PyMODINIT_FUNC PyInit_transcendentals(void);
#endif

#endif /* !__PYX_HAVE__transcendentals */
